import Home from "./Home";
import Profile from "./Profile";
import Search from "./Search";
import Cart from "./Cart";
import ProductDetails from "./ProductDetails";
import LoginPage from "./LoginPage";
import Order from "./Orders";
import Favorites from "./Favorites";
import BackBtn from "../components/products/BackBtn";
import Button from "../components/products/Button";
import SignUp from "./SignUp";
import NewWatchs from "./NewWatchs";
import ProductList from "../components/products/ProductList";
import ProductCardView from "../components/products/ProductCardView";
export { Home,Button,ProductList,ProductCardView,NewWatchs, Profile,SignUp, Search, Cart, BackBtn,ProductDetails,LoginPage,Order,Favorites};
